# This workflow marks issues that have not had recent interaction.

name: 'Close stale issues and PRs'

on:
  # Run at 01:30 UTC every day.
  schedule:
    - cron: '30 1 * * *'
  # Run when manually triggered.
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
        with:
          # Run in debug-only, or dry run mode?
          debug-only: true
          # How many days of in activity, before stale or close?
          days-before-stale: 4
          days-before-close: 14
          # This Action adds the 'stale' label to stale issues.
          stale-issue-label: stale
          # If an issue has the 'keep' label, keep it.
          exempt-issue-labels: keep
          # Write this message to the issue when it is marked stale.
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Use
            the label `keep` to prevent issues from being marked stale.
          #stale-pr-message: |
          # Because stale-pr-message is not provided, PRs will not
          # be marked stale.
